### PR TITLE
Replace sidebar notebook with a stack

### PR DESCRIPTION
**Pull request by danrabbit**
Working towards the icon tab design like the old mockups.

screenshot from 2017-08-20 09 47 33

### CODE REVIEW

**Comment by jeremypw** [comment]
Suggest using an interface between plugins and sidebar widget rather specifying the exact widget.  This would simplify future changes.

**Comment by donadigo** [comment]
Installed the branch, but instead of icons I get labels, did I miss something?

**Comment by danrabbit** [comment]
@donadigo No, I believe the icon name property is new for gtk 3.20, so on 3.18 it will show the title label

**Comment by matzipan** [comment]
Is this blocked?

**Comment by danrabbit** [comment]
Uh no? Blocked by what?

**Comment by matzipan** [comment]
My apologies, I read "I believe the icon name property is new for gtk 3.20, so on 3.18 it will show the title label" as blocked.

**Pull request merged**
